NAME=libplong.so
CPPFLAGS=-g -o $(NAME) -fPIC -shared
FILE=cplong.cpp

$(NAME): $(FILE)
	g++ $(FILE) $(CPPFLAGS)

#NAME=libplong.so
#CPPFLAGS=-g -o $(NAME) -fPIC -shared
#FILE=src/cplong.cpp
#
#$(NAME): $(FILE)
#   g++ $(FILE) $(CPPFLAGS)
# g++ src/cplong.cpp -g -o libplong.so  -fPIC -shared
